const studySuff = {'people':'People',
'%':'Percentage',
'US $':'US dollars',
'tonnes':'Tonnes',
'years':'Years',
'kWh/person':'KWh/person',
'AD':'History',
'Calories':'Calories',
'Feets':'Feets',
'USD':'Economics facts',
'kg':'Weight',
'mph':'Speed',
'$':'Financial facts',
'Cricket facts':'Cricket facts',
'Energy facts':'Energy facts',
'Environmental facts':'Environmental facts',
'Football facts':'Football facts',
'Geopolitical facts':'Geopolitical facts',
'Hollywood facts':'Hollywood facts',
'Music facts':'Music facts',
'Political facts':'Political facts',
'Astronomical facts':'Astronomical facts'}
export default studySuff;